name: Build LiteRT-LM Windows

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-windows:
    name: Build LiteRT-LM C API (Windows)
    runs-on: windows-2022

    steps:
      - name: Checkout Rust bindings
        uses: actions/checkout@v4

      - name: Checkout LiteRT-LM
        uses: actions/checkout@v4
        with:
          repository: google-ai-edge/LiteRT-LM
          path: LiteRT-LM

      - name: Setup Bazelisk
        uses: bazelbuild/setup-bazelisk@v3

      - name: Check environment
        shell: powershell
        run: |
          bazel --version
          git --version
          dir

      - name: Build LiteRT-LM engine
        shell: powershell
        run: |
          cd LiteRT-LM

          bazel build //c:engine `
            --verbose_failures

      - name: Find build output
        shell: powershell
        run: |
          cd LiteRT-LM
          Get-ChildItem -Recurse bazel-bin\c

      - name: Upload engine binaries
        uses: actions/upload-artifact@v4
        with:
          name: litert-lm-windows-x86_64
          path: |
            LiteRT-LM/bazel-bin/c/**
